export const birds = {
  headings: [
    {
      field: "species",
      name: "Species",
    },
    {
      field: "rarity",
      name: "Rarity",
    },
    {
      field: "location",
      name: "Location",
    },
  ],
  rows: [{
    id: 1,
    species: "Greater Flamingo",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 2,
    species: "Red-Naped Ibis",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 3,
    species: "Blue Rock Pigeon",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 4,
    species: "Egrets",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 5,
    species: "Strawberry Finch",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 6,
    species: "Western Yellow Wagtail",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 7,
    species: "Wire Tailed Swallow",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 8,
    species: "Purple Sunbird",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 9,
    species: "Cattle Egret",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 10,
    species: "Green Bee Eater",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 11,
    species: "Small Minivet",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 12,
    species: "White Browed Wagtail",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 13,
    species: "Common Myna",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 14,
    species: "Black Winged Stilt",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 15,
    species: "Red Whiskered Bulbul",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 16,
    species: "Jungle Myna",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 17,
    species: "Fan Tailed Flycatcher",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 18,
    species: "Black Headed Ibis",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 19,
    species: "Kentish Plover",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 20,
    species: "Black Shouldered Kite",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 21,
    species: "Pond Heron",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 22,
    species: "Coppersmith Barbet",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 23,
    species: "Indian Robin",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 24,
    species: "Plumbeous Water Redstart",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 25,
    species: "Common Blackbird",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 26,
    species: "Tickell's Blue Flycatcher",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 27,
    species: "Jungle Babbler",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 28,
    species: "Asian Open Billed Stork",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 29,
    species: "Cinereous Tit",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 30,
    species: "Seagull",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 31,
    species: "Ruddy Shelduck",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 32,
    species: "Wooly Necked Stork",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 33,
    species: "Indian Cuckoo",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 34,
    species: "Bar Headed Goose",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 35,
    species: "Black Kite",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 36,
    species: "Grey Hornbill",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 37,
    species: "Alexandrine Parakeet",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 38,
    species: "Pied Bush Chat",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 39,
    species: "Oriental White-Eye",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 40,
    species: "Indian Peacock",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 41,
    species: "Asian Koel",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 42,
    species: "Little Ringed Plover",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 43,
    species: "Grey Heron",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 44,
    species: "Painted Stork",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 45,
    species: "Large Grey babbler",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 46,
    species: "UNCLASSIFIED",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 47,
    species: "Hume's Leaf Warbler",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 48,
    species: "Cinnereous Tit",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 49,
    species: "Myna",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 50,
    species: "Plain Prinia",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 51,
    species: "Long Tailed Shrike",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 52,
    species: "Small Green Bee Eater",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 53,
    species: "Ashy Prinia",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 54,
    species: "Spotted Owlet",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 55,
    species: "Indian Roller",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 56,
    species: "Indian Golden Oriole",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 57,
    species: "Purple Heron",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 58,
    species: "Laughing Dove",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 59,
    species: "White Thoated Laughingthrush",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 60,
    species: "Western Reef Heron",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 61,
    species: "Oriental Magpie Robin",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 62,
    species: "Hoopoe",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 63,
    species: "Purple Moorhen",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 64,
    species: "Common Stonechat",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 65,
    species: "White Eyed Buzzard",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 66,
    species: "Mottled Wood Owl",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 67,
    species: "Red Vented Bulbul",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 68,
    species: "Baya Weaver",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 69,
    species: "White-Browed Wagtail",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 70,
    species: "Rose Ringed Parakeet",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 71,
    species: "Greater Coucal",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 72,
    species: "Shikra",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 73,
    species: "Indian Silverbill",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 74,
    species: "Rufous Treepie",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 75,
    species: "Yellow Billed Magpie",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 76,
    species: "Unclassified",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 77,
    species: "Little Cormorant",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 78,
    species: "Eurasian Coot",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 79,
    species: "Sykes's Lark",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 80,
    species: "Stripe Throated Yuhina",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 81,
    species: "Scaly Breasted Munia",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 82,
    species: "Siberian Stonchat",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 83,
    species: "White Throated Kingfisher",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 84,
    species: "Spotted Nutcracker",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 85,
    species: "White-Throated Fantail",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 86,
    species: "Crimson Backed Sunbird",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 87,
    species: "Purple Rumped Sunbird",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 88,
    species: "Common Tailorbird",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 89,
    species: "House Crow",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 90,
    species: "Brahminy Starling",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 91,
    species: "Great Cormorant",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 92,
    species: "Black Drongo",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 93,
    species: "Little Grebe",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    {
    id: 94,
    species: "Red Wattled Lapwing",
    rarity: 0,
    location: "Everywhere",
    locationLink: "https://www.google.com",
    },
    ],
}
