export const birds = {
  headings: [
    {
      field: "species",
      name: "Species",
    },
    {
      field: "rarity",
      name: "Rarity",
    },
    {
      field: "location",
      name: "Location",
    },
  ],
  rows: [
    {
      id: 1,
      species: "Greater Flamingo",
      rarity: 3,
      location: "Bhigwan",
      locationLink: "https://www.google.com",
    },
    {
      id: 2,
      species: "Red Naped Ibis",
      rarity: 2,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 3,
      species: "Blue Rock Pigeon",
      rarity: 0,
      location: "Literally Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 4,
      species: "Egrets",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 5,
      species: "Strawberry Finch",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 6,
      species: "Western Yellow Wagtail",
      rarity: 2,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 7,
      species: "Wire Tailed Swallow",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 8,
      species: "Purple Sunbird",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 9,
      species: "Cattle Egret",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 10,
      species: "Green Bee Eater",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 11,
      species: "Small Minivet",
      rarity: 2,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 12,
      species: "White Browed Wagtail",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 13,
      species: "Common Myna",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 14,
      species: "Black Winged Stilt",
      rarity: 1,
      location: "Bhigwan, Kavdi Pat",
      locationLink: "https://www.google.com",
    },
    {
      id: 15,
      species: "Red Whiskered Bulbul",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 16,
      species: "Jungle Myna",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 17,
      species: "Fan Tailed Flycatcher",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 18,
      species: "Black Headed Ibis",
      rarity: 2,
      location: "Bhigwan",
      locationLink: "https://www.google.com",
    },
    {
      id: 19,
      species: "Kentish Plover",
      rarity: 2,
      location: "Bhigwan, Veer Dam, Kavdi Pat",
      locationLink: "https://www.google.com",
    },
    {
      id: 20,
      species: "Black Winged Kite",
      rarity: 2,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 21,
      species: "Pond Heron",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 22,
      species: "Coppersmith Barbet",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 23,
      species: "Indian Robin",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 24,
      species: "Plumbeous Water Redstart",
      rarity: 2,
      location: "Bhutan",
      locationLink: "https://www.google.com",
    },
    {
      id: 25,
      species: "Common Blackbird",
      rarity: 1,
      location: "Sinhagad Valley",
      locationLink: "https://www.google.com",
    },
    {
      id: 26,
      species: "Tickell's Blue Flycatcher",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 27,
      species: "Jungle Babbler",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 28,
      species: "Asian Open Billed Stork",
      rarity: 2,
      location: "Bhigwan, Veer Dam",
      locationLink: "https://www.google.com",
    },
    {
      id: 29,
      species: "Cinereous Tit",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 30,
      species: "Seagull",
      rarity: 2,
      location: "Bhigwan",
      locationLink: "https://www.google.com",
    },
    {
      id: 31,
      species: "Ruddy Shelduck",
      rarity: 1,
      location: "Bhigwan",
      locationLink: "https://www.google.com",
    },
    {
      id: 32,
      species: "Wooly Necked Stork",
      rarity: 2,
      location: "Bhigwan, Pashan Lake",
      locationLink: "https://www.google.com",
    },
    {
      id: 33,
      species: "Indian Cuckoo",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 34,
      species: "Bar Headed Goose",
      rarity: 1,
      location: "Bhigwan",
      locationLink: "https://www.google.com",
    },
    {
      id: 35,
      species: "Black Kite",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 36,
      species: "Grey Hornbill",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 37,
      species: "Alexandrine Parakeet",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 38,
      species: "Pied Bush Chat",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 39,
      species: "Oriental White-Eye",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 40,
      species: "Indian Peacock",
      rarity: 1,
      location: "ARAI, NDA",
      locationLink: "https://www.google.com",
    },
    {
      id: 41,
      species: "Asian Koel",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 42,
      species: "Little Ringed Plover",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 43,
      species: "Grey Heron",
      rarity: 1,
      location: "Bhigwan, Veer Dam, ARAI",
      locationLink: "https://www.google.com",
    },
    {
      id: 44,
      species: "Painted Stork",
      rarity: 2,
      location: "Bhigwan, Veer Dam",
      locationLink: "https://www.google.com",
    },
    {
      id: 45,
      species: "Large Grey Babbler",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 46,
      species: "Crested Serpent Eagle",
      rarity: 1,
      location: "Paabe Ghaat, Sinhagad Valley, Tadoba",
      locationLink: "https://www.google.com",
    },
    {
      id: 47,
      species: "Hume's Leaf Warbler",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 48,
      species: "Changeable Hawk Eagle",
      rarity: 2,
      location: "Bhimashankar",
      locationLink: "https://www.google.com",
    },
    {
      id: 49,
      species: "White Bellied Sea Eagle",
      rarity: 1,
      location: "Goa",
      locationLink: "https://www.google.com",
    },
    {
      id: 50,
      species: "Plain Prinia",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 51,
      species: "Long Tailed Shrike",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 52,
      species: "Brahminy Kite",
      rarity: 1,
      location: "Goa",
      locationLink: "https://www.google.com",
    },
    {
      id: 53,
      species: "Ashy Prinia",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 54,
      species: "Spotted Owlet",
      rarity: 2,
      location: "ARAI, NDA, Pirangut",
      locationLink: "https://www.google.com",
    },
    {
      id: 55,
      species: "Indian Roller",
      rarity: 2,
      location: "ARAI, Mulshi, Tadoba",
      locationLink: "https://www.google.com",
    },
    {
      id: 56,
      species: "Indian Golden Oriole",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 57,
      species: "Purple Heron",
      rarity: 3,
      location: "ARAI",
      locationLink: "https://www.google.com",
    },
    {
      id: 58,
      species: "Laughing Dove",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 59,
      species: "White Thoated Laughingthrush",
      rarity: 0,
      location: "Bhutan",
      locationLink: "https://www.google.com",
    },
    {
      id: 60,
      species: "Western Reef Heron",
      rarity: 2,
      location: "Pashan Lake",
      locationLink: "https://www.google.com",
    },
    {
      id: 61,
      species: "Oriental Magpie Robin",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 62,
      species: "Hoopoe",
      rarity: 1,
      location: "Pirangut, Bhigwan",
      locationLink: "https://www.google.com",
    },
    {
      id: 63,
      species: "Purple Moorhen",
      rarity: 2,
      location: "Bhigwan",
      locationLink: "https://www.google.com",
    },
    {
      id: 64,
      species: "Common Stonechat",
      rarity: 1,
      location: "Mulshi, ARAI",
      locationLink: "https://www.google.com",
    },
    {
      id: 65,
      species: "White Eyed Buzzard",
      rarity: 2,
      location: "Pirangut, Bandhavgarh",
      locationLink: "https://www.google.com",
    },
    {
      id: 66,
      species: "Mottled Wood Owl",
      rarity: 3,
      location: "Tadoba",
      locationLink: "https://www.google.com",
    },
    {
      id: 67,
      species: "Red Vented Bulbul",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 68,
      species: "Baya Weaver",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 69,
      species: "Barn Swallow",
      rarity: 1,
      location: "Mulshi",
      locationLink: "https://www.google.com",
    },
    {
      id: 70,
      species: "Rose Ringed Parakeet",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 71,
      species: "Greater Coucal",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 72,
      species: "Shikra",
      rarity: 1,
      location: "ARAI, Mulshi",
      locationLink: "https://www.google.com",
    },
    {
      id: 73,
      species: "Indian Silverbill",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 74,
      species: "Rufous Treepie",
      rarity: 1,
      location: "ARAI",
      locationLink: "https://www.google.com",
    },
    {
      id: 75,
      species: "Yellow Billed Magpie",
      rarity: 2,
      location: "Bhutan",
      locationLink: "https://www.google.com",
    },
    {
      id: 76,
      species: "Red Rumped Swallow",
      rarity: 1,
      location: "Pabe Ghaat",
      locationLink: "https://www.google.com",
    },
    {
      id: 77,
      species: "Little Cormorant",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 78,
      species: "Eurasian Coot",
      rarity: 1,
      location: "Khadakwasala",
      locationLink: "https://www.google.com",
    },
    {
      id: 79,
      species: "Sykes's Lark",
      rarity: 1,
      location: "ARAI",
      locationLink: "https://www.google.com",
    },
    {
      id: 80,
      species: "Stripe Throated Yuhina",
      rarity: 1,
      location: "Bhutan",
      locationLink: "https://www.google.com",
    },
    {
      id: 81,
      species: "Scaly Breasted Munia",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 82,
      species: "Siberian Stonechat",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 83,
      species: "White Throated Kingfisher",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 84,
      species: "Spotted Nutcracker",
      rarity: 0,
      location: "Bhutan",
      locationLink: "https://www.google.com",
    },
    {
      id: 85,
      species: "Indian Eagle Owl",
      rarity: 2,
      location: "Baner",
      locationLink: "https://www.google.com",
    },
    {
      id: 86,
      species: "Crimson Backed Sunbird",
      rarity: 2,
      location: "Matheran",
      locationLink: "https://www.google.com",
    },
    {
      id: 87,
      species: "Purple Rumped Sunbird",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 88,
      species: "Common Tailorbird",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 89,
      species: "House Crow",
      rarity: 0,
      location: "Literally Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 90,
      species: "Brahminy Starling",
      rarity: 1,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 91,
      species: "Great Cormorant",
      rarity: 1,
      location: "Bhutan",
      locationLink: "https://www.google.com",
    },
    {
      id: 92,
      species: "Black Drongo",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 93,
      species: "Little Grebe",
      rarity: 1,
      location: "ARAI",
      locationLink: "https://www.google.com",
    },
    {
      id: 94,
      species: "Red Wattled Lapwing",
      rarity: 0,
      location: "Everywhere",
      locationLink: "https://www.google.com",
    },
    {
      id: 95,
      species: "Shaheen Falcon",
      rarity: 2,
      location: "ARAI, Pirangut",
      locationLink: "https://www.google.com",
    },
    {
      id: 96,
      species: "Pallid Scops Owl",
      rarity: 5,
      location: "LRK",
      locationLink: "https://www.google.com",
    },
    {
      id: 97,
      species: "Indian Nightjar",
      rarity: 1,
      location: "ARAI",
      locationLink: "https://www.google.com",
    }
  ],
}
