export const germanWords = {
  headings: [
    {
      field: "word",
      name: "German Word",
    },
    {
      field: "meaning",
      name: "Word Meaning",
    },
    {
      field: "example",
      name: "Usage Example",
    },
    {
      field: "translation",
      name: "Translation",
    },
    {
      field: "wordType",
      name: "Type",
    },
  ],
  rows: [
    {
      id: 1,
      word: "das Jahr",
      meaning: "year",
      example: "Das Jahr geht zu Ende",
      translation: "The year is coming to an end",
      wordType: "Noun",
    },
    {
      id: 2,
      word: "das Mal",
      meaning: "time",
      example: "Helmut ist schon zum zweiten Mal in Schweden",
      translation: "Helmut is in Sweden already for the second time",
      wordType: "Noun",
    },
    {
      id: 3,
      word: "das Beispiel",
      meaning: "example",
      example: "Ich könnte zum Beispiel früher kommen",
      translation: "I could come earlier, for example.",
      wordType: "Noun",
    },
    {
      id: 4,
      word: "die Zeit",
      meaning: "time",
      example: "Ich habe keine Zeit",
      translation: "I don't have time",
      wordType: "Noun",
    },
    {
      id: 5,
      word: "die Frau",
      meaning: "woman, wife, Mrs",
      example: "Im Komitee waren nur vier Frauen",
      translation: "There were only 4 women on the committee",
      wordType: "Noun",
    },
    {
      id: 6,
      word: "der Mensch",
      meaning: "human being, man",
      example: "Stammt der Mensch vom Affen ab?",
      translation: "Is human being descended from apes?",
      wordType: "Noun",
    },
    {
      id: 7,
      word: "das Kind",
      meaning: "child",
      example: "Unser Kind geht schon in den Kindergarten",
      translation: "Our child already goes to kindergarten",
      wordType: "Noun",
    },
    {
      id: 8,
      word: "der Tag",
      meaning: "day",
      example: "Sonntag ist der schönste Tag der Woche",
      translation: "Sunday is the best day of the week",
      wordType: "Noun",
    },
    {
      id: 9,
      word: "der Mann",
      meaning: "man",
      example: "Siehst du den Mann dort?",
      translation: "Do you see that man there?",
      wordType: "Noun",
    },
    {
      id: 10,
      word: "das Land",
      meaning: "land, country, state",
      example: "Dänemark ist ein kleines Land in Europe",
      translation: "Denmark is a small country in Europe",
      wordType: "Noun",
    },
    {
      id: 11,
      word: "die Frage",
      meaning: "question",
      example: "Antworte mir bitte auf meine Frage",
      translation: "Please answer my question",
      wordType: "Noun",
    },
    {
      id: 12,
      word: "das Haus",
      meaning: "House",
      example: "Mein Bruder baut sich ein Haus",
      translation: "My brother's building himself a house.",
      wordType: "Noun",
    },
    {
      id: 13,
      word: "der Fall",
      meaning: "fall, case",
      example: "Ich habe so einen Fall noch nicht erlebt",
      translation: "I've never seen a case like this before.",
      wordType: "Noun",
    },
    {
      id: 14,
      word: "die Leute",
      meaning: "people",
      example: "Viele Leute beobachten den Unfall, aber keiner half",
      translation:
        "A lot of people were watching the accident, but nobody helped.",
      wordType: "Noun",
    },
    {
      id: 15,
      word: "die Arbeit",
      meaning: "work",
      example: "Es wartet viel Arbeit auf uns",
      translation: "A lot of work awaits us",
      wordType: "Noun",
    },
    {
      id: 16,
      word: "das Prozent",
      meaning: "percent",
      example: "Diese Prüfung zählt zehn Prozent der Gesamtnote",
      translation: "This exam counts for ten percent of the overall grade.",
      wordType: "Noun",
    },
    {
      id: 17,
      word: "das Hand",
      meaning: "hand",
      example: "Ich habe mir die linke Hand gebrochen",
      translation: "I broke my left hand",
      wordType: "Noun",
    },
    {
      id: 18,
      word: "die Stadt",
      meaning: "city, town",
      example: "Köln ist eine Stadt in Deutschland",
      translation: "Cologne is a city in Germany",
      wordType: "Noun",
    },
    {
      id: 19,
      word: "der Teil",
      meaning: "part",
      example: "Im ersten Teil des Buches werden die Charakter vorgestellt",
      translation:
        "The characters are introduced in the first part of the book",
      wordType: "Noun",
    },
    {
      id: 20,
      word: "das Problem",
      meaning: "problem",
      example: "Wir werden das Problem lösen",
      translation: "We will solve the problem",
      wordType: "Noun",
    },
    {
      id: 21,
      word: "die Welt",
      meaning: "world",
      example: "Eine Reise um die Welt is teuer",
      translation: "A trip around the world is expensive",
      wordType: "Noun",
    },
    {
      id: 22,
      word: "die Recht",
      meaning: "right, law",
      example: "Nach europäischem Recht ist das verboten",
      translation: "According to European law this is forbidden.",
      wordType: "Noun",
    },
    {
      id: 23,
      word: "das Ende",
      meaning: "end",
      example: "Das Ende des Films war traurig",
      translation: "The end of the movie was sad",
      wordType: "Noun",
    },
    {
      id: 24,
      word: "die Schule",
      meaning: "school",
      example: "Sie geht noch zur Schule",
      translation: "She still goes to school",
      wordType: "Noun",
    },
    {
      id: 25,
      word: "die Woche",
      meaning: "week",
      example: "In der nächsten Woche sind Prüfungen",
      translation: "Next week, exams are scheduled",
      wordType: "Noun",
    },
    {
      id: 26,
      word: "der Vater",
      meaning: "father",
      example: "der Vater von Andrea ist gerade vierzig geworden",
      translation: "Andreas father already turned 40",
      wordType: "Noun",
    },
    {
      id: 27,
      word: "die Seite",
      meaning: "side, page",
      example: "Das Buch hat zweihundert Seiten.",
      translation: "The book has 200 pages",
      wordType: "Noun",
    },
    {
      id: 28,
      word: "das Leben",
      meaning: "life",
      example: "Sie versucht, den Tieren das Leben zu retten",
      translation: "She's trying to save the lives of the animals.",
      wordType: "Noun",
    },
    {
      id: 29,
      word: "die Mutter",
      meaning: "mother",
      example: "Meine Mutter ist Chefin eines Konzerns",
      translation: "My mother is the head of a group of companies.",
      wordType: "Noun",
    },
    {
      id: 30,
      word: "der Grund",
      meaning: "reason, basis",
      example: "Du hast keinen Grund, böse zu sein",
      translation: "You have no reason to be angry.",
      wordType: "Noun",
    },
    {
      id: 31,
      word: "das Auge",
      meaning: "eye",
      example: "Max hat sehr schöne Auge",
      translation: "Max has very beautiful eyes",
      wordType: "Noun",
    },
    {
      id: 32,
      word: "das Wort",
      meaning: "word",
      example: "Ich habe das letzte Word nicht verstanden",
      translation: "I didn't get the last word",
      wordType: "Noun",
    },
    {
      id: 33,
      word: "der Geld",
      meaning: "money",
      example: "Ich habe kein Geld",
      translation: "I don't have money",
      wordType: "Noun",
    },
    {
      id: 34,
      word: "die Sache",
      meaning: "thing, matter",
      example: "Die Sache hat sich erledigt",
      translation: "The matter has been settled.",
      wordType: "Noun",
    },
    {
      id: 35,
      word: "die Art",
      meaning: "type, kind",
      example: "Löwe sind eine Art Katzen",
      translation: "Lions are a kind of cats.",
      wordType: "Noun",
    },
    {
      id: 36,
      word: "der Bereich",
      meaning: "area, region",
      example: "In diesem Bereich ist Frau Bitter expertin",
      translation: "Ms Bitter is an expert in this area.",
      wordType: "Noun",
    },
    {
      id: 37,
      word: "der Weg",
      meaning: "path, way",
      example: "Der Weg biegt später nach links ab",
      translation: "The road turns left later",
      wordType: "Noun",
    },
    {
      id: 38,
      word: "die Stunde",
      meaning: "Hour",
      example: "Der Zug hatte zwei Stunden Verspätung",
      translation: "The train ran 2 hours late",
      wordType: "Noun",
    },
    {
      id: 39,
      word: "der Name",
      meaning: "name",
      example: "Mein Name is Charlotte",
      translation: "My name is Charlotte",
      wordType: "Noun",
    },
    {
      id: 40,
      word: "die Geschichte",
      meaning: "history, story",
      example: "Abends liest die Oma den Kindern Geschichten vor",
      translation: "In the evening, grandma reads stories to the children.",
      wordType: "Noun",
    },
    {
      id: 41,
      word: "die Gesellschaft",
      meaning: "society, company",
      example: "Eine multikulturelle Gesellschaft muss tolerant sein",
      translation: "A multicultural society must be tolerant",
      wordType: "Noun",
    },
    {
      id: 42,
      word: "der Kopf",
      meaning: "head",
      example: "Mir tut der Kopf weh",
      translation: "My head hurts",
      wordType: "Noun",
    },
    {
      id: 43,
      word: "das Paar",
      meaning: "pair, couple",
      example: "Agnes hat zwei Paar schöne Schuhe gekauft",
      translation: "Agnes bought two pairs of beautiful shoes",
      wordType: "Noun",
    },
    {
      id: 44,
      word: "die Möglichkeit",
      meaning: "possibility",
      example: "Nach der Konferenz haben Sie die Möglichkeit, essen zu gehen",
      translation:
        "After the conference, you will have the opportunity to eat out",
      wordType: "Noun",
    },
    {
      id: 45,
      word: "das Unternehmen",
      meaning: "enterprise, company",
      example: "Das Unternehmen ging in Konkurs",
      translation: "The company went bankrupt.",
      wordType: "Noun",
    },
    {
      id: 46,
      word: "das Bild",
      meaning: "picture",
      example: "Renates Büro hängt voller Bilder",
      translation: "Renate's office is full of pictures.",
      wordType: "Noun",
    },
    {
      id: 47,
      word: "das Buch",
      meaning: "book",
      example: "Friedrich hat das Buch schon zweimal gelesen",
      translation: "Friedrich has read this book already two times",
      wordType: "Noun",
    },
    {
      id: 48,
      word: "das Wasser",
      meaning: "water",
      example: "Das Wasser ist zu kalt zum Baden",
      translation: "The water is too cold for swimming",
      wordType: "Noun",
    },
    {
      id: 49,
      word: "die Stelle",
      meaning: "place",
      example: "Wir treffen uns an der gleichen Stelle wie letzte Woche",
      translation: "We'll meet at the same place as last week.",
      wordType: "Noun",
    },
    {
      id: 50,
      word: "der Form",
      meaning: "form, shape",
      example: "Das Lindenblatt hat die Form eines Herzens",
      translation: "The lime leaf has the shape of a heart",
      wordType: "Noun",
    },
    {
      id: 51,
      word: "die Entwicklung",
      meaning: "development",
      example:
        "Die Firma hat eine eigene Abteilung für Forschung und Entwicklung",
      translation:
        "The company has its own department for research and development.",
      wordType: "Noun",
    },
    {
      id: 52,
      word: "der Monat",
      meaning: "month",
      example: "Mit sechs Monaten bekommen Babys die ersten Zähne",
      translation: "Babies get their first teeth when they're six months old",
      wordType: "Noun",
    },
    {
      id: 53,
      word: "die Familie",
      meaning: "family",
      example: "Die ganze Familie wohnt in einem Dorf zusammen",
      translation: "The whole family lives together in one village.",
      wordType: "Noun",
    },
    {
      id: 54,
      word: "der Morgen",
      meaning: "morning",
      example: "Am Morgen scheint die Sonne ins Schlafzimmer",
      translation: "In the morning the sun shines into the bedroom",
      wordType: "Noun",
    },
    {
      id: 55,
      word: "der Abend",
      meaning: "evening",
      example: "Im Winter wird es Abends früh dunkel",
      translation: "In winter it gets dark early in the evening",
      wordType: "Noun",
    },
    {
      id: 56,
      word: "die Aufgabe",
      meaning: "task, assignment, job",
      example: "Lösen Sie bitte die folgenden Aufgaben",
      translation: "Please solve the following tasks",
      wordType: "Noun",
    },
    {
      id: 57,
      word: "die Universität, Uni",
      meaning: "university",
      example: "Die Universität wird 60 jahre alt",
      translation: "University turns 60 years old",
      wordType: "Noun",
    },
    {
      id: 58,
      word: "der Sinn",
      meaning: "sense, meaning",
      example: "Mann soll das Leben mit allen Sinnen genießen",
      translation: "Man shall enjoy life with all his senses",
      wordType: "Noun",
    },
    {
      id: 59,
      word: "der Staat",
      meaning: "state",
      example: "Die Steuern bekommt der Staat",
      translation: "The state gets the taxes",
      wordType: "Noun",
    },
    {
      id: 60,
      word: "das Ziel",
      meaning: "destination, goal",
      example: "Hamburg war das Ziel seiner Reise",
      translation: "Hamburg was the destination of his journey",
      wordType: "Noun",
    },
    {
      id: 61,
      word: "der Freund",
      meaning: "friend, boyfriend",
      example: "Franziska wohnt mit ihrem Freund zusammen",
      translation: "Franziska lives with her boyfriend",
      wordType: "Noun",
    },
    {
      id: 62,
      word: "das Thema",
      meaning: "subject, topic, theme",
      example: "Ich würde gern das Thema wechseln",
      translation: "I'd like to change the subject.",
      wordType: "Noun",
    },
    {
      id: 63,
      word: "die Person",
      meaning: "person",
      example: "Dieser Tisch ist ab 20 Uhr für acht Personen reserviert",
      translation: "This table is reserved from 20 o'clock for eight persons.",
      wordType: "Noun",
    },
    {
      id: 64,
      word: "die Nacht",
      meaning: "night",
      example: "Sie haben die ganze Nacht getanzt",
      translation: "They've been dancing all night.",
      wordType: "Noun",
    },
    {
      id: 65,
      word: "der Ding",
      meaning: "thing",
      example: "Gib mr mal das Ding da!",
      translation: "Give me that thing!",
      wordType: "Noun",
    },
    {
      id: 66,
      word: "der Raum",
      meaning: "room, space",
      example: "Das Wohnzimmer ist der größte Raum in der Wohnung",
      translation: "The living room is the largest room in the apartment",
      wordType: "Noun",
    },
    {
      id: 67,
      word: "der Blick",
      meaning: "view, look, glance",
      example:
        "Von der Turmspitze hat man einen schönen Blick über die ganze Stadt",
      translation:
        "From the top of the tower you have a beautiful view over the whole city.",
      wordType: "Noun",
    },
    {
      id: 68,
      word: "der Platz",
      meaning: "place, room, square",
      example: "Ich habe nicht genug Platz",
      translation: "I don't have enough room",
      wordType: "Noun",
    },
    {
      id: 69,
      word: "die Zahl",
      meaning: "number",
      example: "Eine große Zahl von Jugendlichen raucht",
      translation: "A large number of young people smoke",
      wordType: "Noun",
    },
    {
      id: 70,
      word: "das System",
      meaning: "system",
      example: "Neben der Demokratie gibt es noch andere politische Systeme",
      translation: "There are other political systems besides democracy",
      wordType: "Noun",
    },
    {
      id: 71,
      word: "die Uhr",
      meaning: "hour, watch",
      example: "Es ist genau zehn Uhr",
      translation: "It's ten o'clock exactly.",
      wordType: "Noun",
    },
    {
      id: 72,
      word: "die Eltern",
      meaning: "parents",
      example: "In den Ferien fahren wir mit den Eltern an die Ostsee",
      translation:
        "During the holidays we will go with our parents to the Baltic Sea",
      wordType: "Noun",
    },
    {
      id: 73,
      word: "die Straße",
      meaning: "street",
      example: "Die Straße wird neu gebaut",
      translation: "The road is newly built",
      wordType: "Noun",
    },
    {
      id: 74,
      word: "die Minute",
      meaning: "minute",
      example: "Der Kuchen muss zwanzig Minuten backen",
      translation: "The cake must bake for twenty minutes.",
      wordType: "Noun",
    },
    {
      id: 75,
      word: "die Gruppe",
      meaning: "group",
      example: "Zu den Workshops treffen wir uns in kleinen Gruppen",
      translation: "For the workshops we gather in small groups",
      wordType: "Noun",
    },
    {
      id: 76,
      word: "das Wert",
      meaning: "value",
      example: "Die Aktie hat an Wert verloren",
      translation: "The share price has lost value",
      wordType: "Noun",
    },
    {
      id: 77,
      word: "die Gesicht",
      meaning: "face",
      example: "Sie hat ein rundes, immer freundliches Gesicht",
      translation: "She has a round, always friendly face.",
      wordType: "Noun",
    },
    {
      id: 78,
      word: "die Sprache",
      meaning: "language",
      example: "Die deutsche Sprache hat den Ruf, schwierig zu sein",
      translation: "The German language has the reputation of being difficult.",
      wordType: "Noun",
    },
    {
      id: 79,
      word: "der Anfang",
      meaning: "beginning",
      example: "Am Anfang war das Wort",
      translation: "In the beginning was the word",
      wordType: "Noun",
    },
    {
      id: 80,
      word: "der Ort",
      meaning: "place, town, location",
      example: "Bad Harzburg ist ein kleiner Ort im Harz",
      translation: "Bad Harzburg is a small town in the Harz Mountains",
      wordType: "Noun",
    },
    {
      id: 81,
      word: "der Moment",
      meaning: "moment",
      example: "Warte noch einen Moment!",
      translation: "Wait a minute!",
      wordType: "Noun",
    },
    {
      id: 82,
      word: "die Folge",
      meaning: "result, consequence",
      example: "Die Folge davon war, dass er arbeitslos wurde",
      translation: "The result was that he lost his job",
      wordType: "Noun",
    },
    {
      id: 83,
      word: "das Interesse",
      meaning: "interest",
      example: "Sind Studiengebühren im Interesse der Studenten?",
      translation: "Are tuition fees in the interest of students?",
      wordType: "Noun",
    },
    {
      id: 84,
      word: "die Rolle",
      meaning: "role, roll",
      example: "Gustav Gründgens überzeugte in der Rolle des Faust",
      translation: "Gustav Gründgens was convinced in the role of Faust",
      wordType: "Noun",
    },
    {
      id: 85,
      word: "die Tür",
      meaning: "door",
      example: "Sein Name steht an die Tür",
      translation: "His name is on the door.",
      wordType: "Noun",
    },
    {
      id: 86,
      word: "der Schüler",
      meaning: "student",
      example: "Alle Schüler treffen sich donnerstags in der Aula",
      translation: "All students meet in the auditorium on Thursdays.",
      wordType: "Noun",
    },
    {
      id: 87,
      word: "die Bedeutung",
      meaning: "meaning, significance",
      example: "Was hat das für eine Bedeutung?",
      translation: "What does that mean?",
      wordType: "Noun",
    },
    {
      id: 88,
      word: "der Text",
      meaning: "text",
      example: "Der Text ist zu Lang",
      translation: "The text is too long",
      wordType: "Noun",
    },
    {
      id: 89,
      word: "das Ergebnis",
      meaning: "result, outcome",
      example: "Die Projektgruppe stellt ihre Ergebnisse vor",
      translation: "The project group presents its results",
      wordType: "Noun",
    },
    {
      id: 90,
      word: "der Krieg",
      meaning: "war",
      example: "Die Soldaten ziehen in den Krieg",
      translation: "The soldiers go to war",
      wordType: "Noun",
    },
    {
      id: 91,
      word: "die Weise",
      meaning: "way, manner",
      example: "Auf welche Weise lösen wir das Problem am schnellsten?",
      translation: "What is the quickest way to solve the problem?",
      wordType: "Noun",
    },
    {
      id: 92,
      word: "die Regierung",
      meaning: "rule, government",
      example: "Die Regierung sitzt in Berlin",
      translation: "The government is in Berlin",
      wordType: "Noun",
    },
    {
      id: 93,
      word: "der Stück",
      meaning: "piece",
      example: "Ich möchte noch ein Stück Kuchen",
      translation: "I'd like another piece of cake.",
      wordType: "Noun",
    },
    {
      id: 94,
      word: "die Wohnung",
      meaning: "apartment, flat",
      example: "Die Wohnung ist im dritten Stock",
      translation: "The apartment is on the third floor",
      wordType: "Noun",
    },
    {
      id: 95,
      word: "das Gespräch",
      meaning: "conversation",
      example: "Ein vernünftiges Gespräch war nichts mehr möglich",
      translation: "A reasonable conversation was no longer possible",
      wordType: "Noun",
    },
    {
      id: 96,
      word: "sagen",
      meaning: "to say",
      example: "Conny sagt ihrem Man die Wahrheit",
      translation: "Conny tells her husband the truth",
      wordType: "Verb",
    },
    {
      id: 97,
      word: "machen",
      meaning: "to make",
      example: "Ich mache meine Hausaufgaben",
      translation: "I am doing my homework",
      wordType: "Verb",
    },
    {
      id: 98,
      word: "geben",
      meaning: "to give",
      example: "Ich gebe dir das Buch",
      translation: "I am giving you the book",
      wordType: "Verb",
    },
    {
      id: 99,
      word: "kommen",
      meaning: "to come",
      example: "Wir kommen morgen zu dir",
      translation: "We will come to you tomorrow",
      wordType: "Verb",
    },
    {
      id: 100,
      word: "gehen",
      meaning: "to go",
      example: "Wir gehen ins Kino",
      translation: "We are going to the movies",
      wordType: "Verb",
    },
    {
      id: 101,
      word: "wissen",
      meaning: "to know",
      example: "Woher weißt du das?",
      translation: "Where do you know this from?",
      wordType: "Verb",
    },
    {
      id: 102,
      word: "sehen",
      meaning: "to see",
      example: "Mark sieht ohne Brille nichts",
      translation: "Mark sees nothing without his glasses",
      wordType: "Verb",
    },
    {
      id: 103,
      word: "stehen",
      meaning: "to stand,",
      example: "Der Maler steht auf dem Balkon",
      translation: "The painter stands on the balcony",
      wordType: "Verb",
    },
    {
      id: 104,
      word: "finden",
      meaning: "to find",
      example: "Wir finden keine Lösung",
      translation: "We are failing to find a solution",
      wordType: "Verb",
    },
    {
      id: 105,
      word: "bleiben",
      meaning: "to stay, remain",
      example: "Du kannst bis morgen bleiben",
      translation: "You can stay till tomorrow",
      wordType: "Verb",
    },
    {
      id: 106,
      word: "liegen",
      meaning: "to lie",
      example: "Der Kranke liegt im Bett",
      translation: "The patient lies in bed",
      wordType: "Verb",
    },
    {
      id: 107,
      word: "heißen",
      meaning: "to be called",
      example: "Sie heißt Anja",
      translation: "Her name is Anja",
      wordType: "Verb",
    },
    {
      id: 108,
      word: "denken",
      meaning: "to think",
      example: "Wir denken an dich",
      translation: "We think of you",
      wordType: "Verb",
    },
    {
      id: 109,
      word: "nehmen",
      meaning: "to take",
      example: "Kannst du den Koffern nehmen?",
      translation: "Can you take the suitcase?",
      wordType: "Verb",
    },
    {
      id: 110,
      word: "tun",
      meaning: "to do",
      example: "Wir tun nur unsere Pflicht",
      translation: "We're just doing our duty",
      wordType: "Verb",
    },
    {
      id: 111,
      word: "glauben",
      meaning: "to believe",
      example: "Glaubst du uns?",
      translation: "Do you believe us?",
      wordType: "Verb",
    },
    {
      id: 112,
      word: "halten",
      meaning: "to hold",
      example: "Er hält eine Blume in der Hand",
      translation: "He is holding a flower in his hand",
      wordType: "Verb",
    },
    {
      id: 113,
      word: "nennen",
      meaning: "to name, call",
      example: "Sie nennen ihren Sohn Max",
      translation: "They will call their son Max",
      wordType: "Verb",
    },
    {
      id: 114,
      word: "mögen",
      meaning: "to like",
      example: "Ich mag Äpfel",
      translation: "I like apples",
      wordType: "Verb",
    },
    {
      id: 115,
      word: "zeigen",
      meaning: "to show",
      example: "Der Stadtführer zeigt den Touristen die Stadt",
      translation: "The city guide shows the tourists the city",
      wordType: "Verb",
    },
    {
      id: 116,
      word: "führen",
      meaning: "to lead",
      example: "Die Straße führt ins nächste Dorf",
      translation: "The road leads to the next village",
      wordType: "Verb",
    },
    {
      id: 117,
      word: "sprechen",
      meaning: "to speak",
      example: "Ich spreche mit dir",
      translation: "I am speaking with you",
      wordType: "Verb",
    },
    {
      id: 118,
      word: "bringen",
      meaning: "to bring",
      example: "Er bringt seiner Freundin Blumen",
      translation: "He is bringing flower to his girlfriend",
      wordType: "Verb",
    },
    {
      id: 119,
      word: "leben",
      meaning: "to live",
      example: "Tobi lebt in Berlin",
      translation: "Tobi lives in Berlin",
      wordType: "Verb",
    },
    {
      id: 120,
      word: "fahren",
      meaning: "to drive, ride, go",
      example: "Jan fahrt gern Fahrrad",
      translation: "Jan likes to ride a bike",
      wordType: "Verb",
    },
    {
      id: 121,
      word: "meinen",
      meaning: "to think, have an opinion",
      example: "Was meint ihr zu dieser Idee?",
      translation: "What do you think about this idea?",
      wordType: "Verb",
    },
    {
      id: 122,
      word: "fragen",
      meaning: "to ask",
      example: "Max hat nach dir gefragt",
      translation: "Max asked for you",
      wordType: "Verb",
    },
    {
      id: 123,
      word: "gelten",
      meaning: "to be valid",
      example: "Dieser Fahrplan gilt nicht mehr",
      translation: "This timetable is no longer valid",
      wordType: "Verb",
    },
    {
      id: 124,
      word: "stellen",
      meaning: "to place, set",
      example: "Ich stelle den Teller auf den Tisch",
      translation: "I am putting a plat on the table",
      wordType: "Verb",
    },
    {
      id: 125,
      word: "spielen",
      meaning: "to play",
      example: "Die Kinder spielen draußen",
      translation: "The children are playing outside",
      wordType: "Verb",
    },
    {
      id: 126,
      word: "arbeiten",
      meaning: "to work",
      example: "Er arbeitet seit zwei Jahren in dieser Firma",
      translation: "He has been working in this company for two years",
      wordType: "Verb",
    },
    {
      id: 127,
      word: "brauchen",
      meaning: "to need",
      example: "Brauchst du Hilfe?",
      translation: "Do you need help?",
      wordType: "Verb",
    },
    {
      id: 128,
      word: "folgen",
      meaning: "to follow",
      example: "Ich folge deinem Rat",
      translation: "I follow your advice",
      wordType: "Verb",
    },
    {
      id: 129,
      word: "lernen",
      meaning: "to learn",
      example: "Sie lernt Deutsch",
      translation: "She is learning German",
      wordType: "Verb",
    },
    {
      id: 130,
      word: "bestehen",
      meaning: "to exist",
      example: "Die Firma besteht seit 2004",
      translation: "The company exists since 2004",
      wordType: "Verb",
    },
    {
      id: 131,
      word: "verstehen",
      meaning: "to understand",
      example: "Jan versteht kein Englisch",
      translation: "Jan does not understand any English",
      wordType: "Verb",
    },
    {
      id: 132,
      word: "setzen",
      meaning: "to set, place, put",
      example:
        "Wenn man die Daten zueinander in die Beziehung setzt, kommt man zu interessanten Ergebnissen",
      translation:
        "If you connect the data together, you get interesting results.",
      wordType: "Verb",
    },
    {
      id: 133,
      word: "bekommen",
      meaning: "to get, receive",
      example: "Wir bekomme selten Post",
      translation: "We rarely get mail",
      wordType: "Verb",
    },
    {
      id: 134,
      word: "beginnen",
      meaning: "to begin",
      example: "Max beginnt im Herbst sein Studium",
      translation: "Max begins his studies in autumn",
      wordType: "Verb",
    },
    {
      id: 135,
      word: "erzählen",
      meaning: "to tell",
      example: "Die Mutter erzählt ihren Kindern ein Märchen",
      translation: "The mother tells her children a fairytale",
      wordType: "Verb",
    },
    {
      id: 136,
      word: "versuchen",
      meaning: "to try, attempt",
      example: "Ich versuche, die Prüfung dieses Mal zu bestehen",
      translation: "I will try to pass this exam this time.",
      wordType: "Verb",
    },
    {
      id: 137,
      word: "schreiben",
      meaning: "to write",
      example: "Romeo schreibt Julia einen Liebesbrief",
      translation: "Romeo is writing a love letter to Juliet",
      wordType: "Verb",
    },
    {
      id: 138,
      word: "laufen",
      meaning: "to run",
      example: "Erwin läuft jeden Tag fünf Runden im Park",
      translation: "Erwin runs five laps in the park every day",
      wordType: "Verb",
    },
    {
      id: 139,
      word: "erklären",
      meaning: "to explain",
      example: "Der Lehrer erklärt seinen Schülern eine chemische Formel",
      translation: "The teacher explains a chemical formula to the students",
      wordType: "Verb",
    },
    {
      id: 140,
      word: "entsprechen",
      meaning: "to correspond, match",
      example: "Der Anzug entspricht nicht meinen Vorstellungen",
      translation: "The suit doesn't match my expectation.",
      wordType: "Verb",
    },
    {
      id: 141,
      word: "sitzen",
      meaning: "to sit",
      example: "Auf dem Sofa sitzt der Kater und putzt sich",
      translation: "The cat sits on the sofa and cleans itself",
      wordType: "Verb",
    },
    {
      id: 142,
      word: "ziehen",
      meaning: "to pull, move",
      example: "Man muss an der Tür ziehen, um sie zu öffnen",
      translation: "You must pull the door to open it",
      wordType: "Verb",
    },
    {
      id: 143,
      word: "scheinen",
      meaning: "to shine, seem, appear",
      example: "der Sonne scheint",
      translation: "The sun is shining",
      wordType: "Verb",
    },
    {
      id: 144,
      word: "fallen",
      meaning: "to fall",
      example: "Lass die Vase bitte nicht fallen!",
      translation: "Please don't let the vase fall!",
      wordType: "Verb",
    },
    {
      id: 145,
      word: "gehören",
      meaning: "to belong",
      example: "der Koffer gehört mir",
      translation: "The suitcase belongs to me",
      wordType: "Verb",
    },
    {
      id: 146,
      word: "entstehen",
      meaning: "to originate, develop",
      example: "Wirbelstürme entstehen über dem Meer",
      translation: "Hurricanes form over the sea",
      wordType: "Verb",
    },
    {
      id: 147,
      word: "erhalten",
      meaning: "to receive",
      example: "Den Brief habe ich am Mittwoch erhalten",
      translation: "I received the letter on Wednesday",
      wordType: "Verb",
    },
    {
      id: 148,
      word: "treffen",
      meaning: "to meet",
      example: "Wir treffen uns morgen Mittag auf dem Markt",
      translation: "We will meet each other tomorrow noon at the market.",
      wordType: "Verb",
    },
    {
      id: 149,
      word: "suchen",
      meaning: "to search, look for",
      example: "Ich habe meinen Sonnenbrille stundenlang gesucht",
      translation: "I have searched for my sunglasses for hours",
      wordType: "Verb",
    },
    {
      id: 150,
      word: "legen",
      meaning: "to lay, put",
      example: "Die Mutter legt das Baby ins Bett",
      translation: "The mother puts the baby on the bed",
      wordType: "Verb",
    },
    {
      id: 151,
      word: "vorstellen",
      meaning: "to introduce, imagine",
      example: "Der Manager stellt das neue Konzept vor",
      translation: "The manage is introducing the new concept",
      wordType: "Verb",
    },
    {
      id: 152,
      word: "handeln",
      meaning: "to deal, trade, be about",
      example: "Der Roman handelt von einer modernen Familie",
      translation: "The novel is about a modern family",
      wordType: "Verb",
    },
    {
      id: 153,
      word: "erreichen",
      meaning: "to achieve, reach",
      example: "Nach vier Stunden erreichten wir den Berggipfel",
      translation: "After four hours we reached the mountaintop",
      wordType: "Verb",
    },
    {
      id: 154,
      word: "tragen",
      meaning: "to carry, wear",
      example: "Sie trägt im Sommer gern Kleider",
      translation: "She likes to wear dresses in summer.",
      wordType: "Verb",
    },
    {
      id: 155,
      word: "schaffen",
      meaning: "to manage, create",
      example: "Ich schaffe meine Arbeit nicht",
      translation: "I'm not managing to do my job",
      wordType: "Verb",
    },
    {
      id: 156,
      word: "lesen",
      meaning: "to read",
      example: "Antina liest gern Game of Thrones Bücher",
      translation: "Antina likes to read Game of Thrones books",
      wordType: "Verb",
    },
    {
      id: 157,
      word: "verlieren",
      meaning: "to lose",
      example: "Die Kirche verliert an Einfluss",
      translation: "The church is losing its influence",
      wordType: "Verb",
    },
    {
      id: 158,
      word: "darstellen",
      meaning: "to depict, portray",
      example: "Das Bild stellt eine Winterlandschaft dar.",
      translation: "The image depicts a winter landscape",
      wordType: "Verb",
    },
    {
      id: 159,
      word: "erkennen",
      meaning: "to recognize, admit",
      example: "Ich kann es nicht erkennen, ich sehe schlecht",
      translation: "I cannot quite see it, I have a poor eyesight",
      wordType: "Verb",
    },
    {
      id: 160,
      word: "entwickeln",
      meaning: "to develop",
      example: "Schmetterlinge entwickeln sich aus Raupen",
      translation: "Butterflies develop from caterpillars",
      wordType: "Verb",
    },
    {
      id: 161,
      word: "reden",
      meaning: "to talk",
      example: "Ich möchte jetzt nicht darüber reden",
      translation: "I don't want to talk about it now",
      wordType: "Verb",
    },
    {
      id: 162,
      word: "aussehen",
      meaning: "to appear, look",
      example: "Sie sieht aus wie ihre Großmutter",
      translation: "She looks like her grandmother",
      wordType: "Verb",
    },
    {
      id: 163,
      word: "erscheinen",
      meaning: "to appear",
      example: "Die ersten Sterne erscheinen am Himmel",
      translation: "The first stars are appearing in the sky",
      wordType: "Verb",
    },
    {
      id: 164,
      word: "bilden",
      meaning: "to form, educate",
      example: "Den Höhepunkt des Festes bildet das abendliche Feuerwerk",
      translation:
        "The highlight of the festival is the evening fireworks show",
      wordType: "Verb",
    },
    {
      id: 165,
      word: "anfangen",
      meaning: "to begin",
      example: "Das Theaterstück fängt gleich an",
      translation: "The play's about to start",
      wordType: "Verb",
    },
    {
      id: 166,
      word: "erwarten",
      meaning: "to expect",
      example: "Unser Chef erwartet großes Engagement von seinen Mitarbeitern",
      translation: "Our boss expects great commitment from his employees",
      wordType: "Verb",
    },
    {
      id: 167,
      word: "wohnen",
      meaning: "to live",
      example: "Mark wohnt schon dreizehn Jahre in Deutschland",
      translation: "Mark has been living in Germany already for 14 years",
      wordType: "Verb",
    },
    {
      id: 168,
      word: "betreffen",
      meaning: "to affect, concern",
      example: "Das betrifft alle Abiturienten dieses Jahrgangs",
      translation:
        "That concerns all high school graduates of this year's class",
      wordType: "Verb",
    },
    {
      id: 169,
      word: "warten",
      meaning: "to wait",
      example: "Die Kinder warten voller Ungeduld auf Weihnachten",
      translation: "The children are waiting impatiently for Christmas.",
      wordType: "Verb",
    },
    {
      id: 170,
      word: "vergehen",
      meaning: "to pass (about time)",
      example: "Wie die Zeit vergeht.",
      translation: "How the time flies.",
      wordType: "Verb",
    },
    {
      id: 171,
      word: "helfen",
      meaning: "to help",
      example: "Kinder sollten im Haushalt helfen",
      translation: "Children should help with the household",
      wordType: "Verb",
    },
    {
      id: 172,
      word: "gewinnen",
      meaning: "to win, gain",
      example: "Sie möchte eine Medaille gewinnen",
      translation: "She wants to win a medal",
      wordType: "Verb",
    },
    {
      id: 173,
      word: "schließen",
      meaning: "to close",
      example: "Schließen Sie jetzt bitte die Augen",
      translation: "Please close your eyes",
      wordType: "Verb",
    },
    {
      id: 174,
      word: "fühlen",
      meaning: "to feel",
      example: "Sie fühlt sich schlecht",
      translation: "She is not feeling well",
      wordType: "Verb",
    },
    {
      id: 175,
      word: "bieten",
      meaning: "to offer",
      example:
        "Nach dem Vortrag bietet sich die Gelegenheit zu einem Stadtrundgang",
      translation:
        "After the lecture you will have the opportunity to take a tour of the city.",
      wordType: "Verb",
    },
    {
      id: 176,
      word: "interessieren",
      meaning: "to interest",
      example: "Das fünfte Kapitel interessiert uns heute besonders",
      translation: "The fifth chapter is especially interesting for us today",
      wordType: "Verb",
    },
    {
      id: 177,
      word: "interessieren sich",
      meaning: "to be interested",
      example: "Hans interessiert sich für Architektur",
      translation: "Hans is interested in Architecture",
      wordType: "Verb",
    },
    {
      id: 178,
      word: "erinnern",
      meaning: "to remind",
      example: "Ich werde dich daran erinnern",
      translation: "I will remind you about it",
      wordType: "Verb",
    },
    {
      id: 179,
      word: "erinnern sich",
      meaning: "to remember",
      example: "Ich kann mich nicht daran erinnern",
      translation: "I cannot remember it",
      wordType: "Verb",
    },
    {
      id: 180,
      word: "ergeben",
      meaning: "to result in",
      example: "Vier plus vier ergibt acht",
      translation: "4 plus 4 equals 8",
      wordType: "Verb",
    },
    {
      id: 181,
      word: "anbieten",
      meaning: "to offer",
      example: "Die Firma bietet einen rabatt von 10% an",
      translation: "The company is offering a 10% discount",
      wordType: "Verb",
    },
    {
      id: 182,
      word: "studieren",
      meaning: "to study",
      example: "Nach ihrem Abitur will Melanie Psychologie studieren",
      translation: "After her graduation, Melanie wants to study psychology",
      wordType: "Verb",
    },
    {
      id: 183,
      word: "verbinden",
      meaning: "to connect, link",
      example: "Verbinden Sie ihre Smartwatch mit dem Handy",
      translation: "Connect your smartwatch to your mobile phone",
      wordType: "Verb",
    },
    {
      id: 184,
      word: "ansehen",
      meaning: "to look at, watch",
      example: "Ich sehe mir gleich die Nachrichten an",
      translation: "I'm about to watch the news.",
      wordType: "Verb",
    },
    {
      id: 185,
      word: "fehlen",
      meaning: "to lack, be missing, be absent",
      example: "Es fehlt die Unterschrift",
      translation: "The signature is missing",
      wordType: "Verb",
    },
    {
      id: 186,
      word: "bedeuten",
      meaning: "to mean",
      example: "Was bedeutet das?",
      translation: "What does that mean?",
      wordType: "Verb",
    },
    {
      id: 187,
      word: "vergleichen",
      meaning: "to compare",
      example: "Vergleich doch mal die Preise",
      translation: "Please compare the prices one more time",
      wordType: "Verb",
    },
    {
      id: 188,
      word: "steigen",
      meaning: "to climb, increase",
      example: "Die Aktien steigen",
      translation: "The stocks are rising",
      wordType: "Verb",
    },
    {
      id: 189,
      word: "verlassen",
      meaning: "to leave",
      example: "Wir verlassen das Haus um 8 Uhr",
      translation: "We will leave the house at 8",
      wordType: "Verb",
    },
    {
      id: 190,
      word: "verlassen sich",
      meaning: "To depend, rely on",
      example: "Ich verlasse mich auf dich",
      translation: "I rely on you",
      wordType: "Verb",
    },
    {
      id: 191,
      word: "ganz",
      meaning: "whole, entire",
      example: "Ich habe eine ganze Pizza gegessen",
      translation: "I ate an entire pizza",
      wordType: "Adjective",
    },
    {
      id: 192,
      word: "groß",
      meaning: "big, large",
      example: "Berlin ist eine große Stadt",
      translation: "Berlin is a big city",
      wordType: "Adjective",
    },
    {
      id: 193,
      word: "gut",
      meaning: "good",
      example: "Das Eis schmeckt gut",
      translation: "The ice cream tastes good",
      wordType: "Adjective",
    },
    {
      id: 194,
      word: "neu",
      meaning: "new",
      example: "Ruben braucht neue Schuhe",
      translation: "Ruben needs new shoes",
      wordType: "Adjective",
    },
    {
      id: 195,
      word: "erste",
      meaning: "first",
      example: "Der erste Zug fährt um sechs Uhr ab",
      translation: "The first train leaves at six o'clock",
      wordType: "Adjective",
    },
    {
      id: 196,
      word: "lang",
      meaning: "long",
      example: "Heute war ein langer Tag",
      translation: "Today was a long day",
      wordType: "Adjective",
    },
    {
      id: 197,
      word: "klein",
      meaning: "small, little",
      example: "Ein kleines Auto passt in jede Parklücke",
      translation: "A small car fits into every parking space",
      wordType: "Adjective",
    },
    {
      id: 198,
      word: "alt",
      meaning: "old",
      example: "Neben dem Haus steht ein alter Baum",
      translation: "Next to the house is an old tree",
      wordType: "Adjective",
    },
    {
      id: 199,
      word: "hoch",
      meaning: "high, tall",
      example: "Der Brocken ist ein hoher Berg",
      translation: "The Brocken is a high mountain",
      wordType: "Adjective",
    },
    {
      id: 200,
      word: "einfach",
      meaning: "simple, easy",
      example: "Pudding kochen ist eine einfache Aufgabe",
      translation: "Pudding cooking is a simple task",
      wordType: "Adjective",
    },
    {
      id: 201,
      word: "letzte",
      meaning: "last",
      example: "Pauline kam als letzte ins Ziel",
      translation: "Pauline was the last one to finish",
      wordType: "Adjective",
    },
    {
      id: 202,
      word: "gleich",
      meaning: "same",
      example: "Da haben die Eltern die gleiche Meinung",
      translation: "The parents have the same opinion",
      wordType: "Adjective",
    },
    {
      id: 203,
      word: "möglich",
      meaning: "possible",
      example: "Ist es möglich, später zu bezahlen?",
      translation: "Is it possible to pay later?",
      wordType: "Adjective",
    },
    {
      id: 204,
      word: "eigen",
      meaning: "own",
      example: "Auch Kinder dürfen ihre eigene Meinung haben",
      translation: "Even children can have their own opinion",
      wordType: "Adjective",
    },
    {
      id: 205,
      word: "schön",
      meaning: "beautiful",
      example: "Ein Buch ist ein schönes Geschenk",
      translation: "A book is a beautiful gift",
      wordType: "Adjective",
    },
    {
      id: 206,
      word: "spät",
      meaning: "late",
      example: "Es ist schon spät",
      translation: "It's getting late",
      wordType: "Adjective",
    },
    {
      id: 207,
      word: "wichtig",
      meaning: "important",
      example: "Eine wichtige Besprechung fällt heute aus",
      translation: "An important meeting has been cancelled today",
      wordType: "Adjective",
    },
    {
      id: 208,
      word: "weitere",
      meaning: "additional, further",
      example: "Gibt es noch weitere Fragen?",
      translation: "Are there any further questions?",
      wordType: "Adjective",
    },
    {
      id: 209,
      word: "genau",
      meaning: "exactly",
      example: "Wie spät ist es genau?",
      translation: "What time is it exactly?",
      wordType: "Adjective",
    },
    {
      id: 210,
      word: "jung",
      meaning: "young",
      example: "Da stand ein junger Mann vor der Tür",
      translation: "There was a young man at the door",
      wordType: "Adjective",
    },
    {
      id: 211,
      word: "kurz",
      meaning: "short",
      example: "Isabel hat kurze Haare",
      translation: "Isabel has short hair",
      wordType: "Adjective",
    },
    {
      id: 212,
      word: "stark",
      meaning: "strong",
      example: "Angela ist eine starke Frau",
      translation: "Angela is a strong woman",
      wordType: "Adjective",
    },
    {
      id: 213,
      word: "richtig",
      meaning: "correct",
      example: "Das richtige Antwort wusste niemand",
      translation: "Nobody knew the right answer",
      wordType: "Adjective",
    },
    {
      id: 214,
      word: "verschieden",
      meaning: "different, diverse",
      example: "Ihre Töchter sind sehr verschieden",
      translation: "Her daughters are very different",
      wordType: "Adjective",
    },
    {
      id: 215,
      word: "bestimmt",
      meaning: "specific, certain",
      example: "Ich suche ein bestimmtes Buch",
      translation: "I'm looking for a certain book",
      wordType: "Adjective",
    },
    {
      id: 216,
      word: "besser",
      meaning: "better",
      example: "Sie kann besser schwimmen als wir",
      translation: "She can swim better than we can",
      wordType: "Adjective",
    },
    {
      id: 217,
      word: "schnell",
      meaning: "fast",
      example: "Ein schnelles Auto verbraucht auch meist viel Benzin",
      translation: "A fast car also usually uses a lot of petrol",
      wordType: "Adjective",
    },
    {
      id: 218,
      word: "sicher",
      meaning: "safe, secure",
      example: "Diese Methode ist absolut sicher",
      translation: "This method is absolutely safe",
      wordType: "Adjective",
    },
    {
      id: 219,
      word: "nächste",
      meaning: "next",
      example: "Nächste Woche ist Ostern",
      translation: "Next week is Easter",
      wordType: "Adjective",
    },
    {
      id: 220,
      word: "politisch",
      meaning: "political",
      example: "Markus ist politisch sehr aktiv",
      translation: "Markus is politically very active",
      wordType: "Adjective",
    },
    {
      id: 221,
      word: "klar",
      meaning: "clear",
      example: "Boris hat klare Vorstellungen von seinem Traumberuf",
      translation: "Boris clearly knows what his dream job is",
      wordType: "Adjective",
    },
    {
      id: 222,
      word: "schwer",
      meaning: "difficult, heavy",
      example: "Esel können schwere Lasten tragen",
      translation: "Donkeys can carry heavy loads",
      wordType: "Adjective",
    },
    {
      id: 223,
      word: "einzeln",
      meaning: "individual",
      example: "Die Geburtstagsgäste kamen alle einzeln",
      translation: "The birthday guests all came one at a time",
      wordType: "Adjective",
    },
    {
      id: 224,
      word: "bekannt",
      meaning: "well-known",
      example: "Heike Makatsch ist eine bekannte deutsche Schauspielerin",
      translation: "Heike Makatsch is a well-known German actress",
      wordType: "Adjective",
    },
    {
      id: 225,
      word: "leicht",
      meaning: "light, easy",
      example: "Kinder erziehen ist keine leichte Aufgabe",
      translation: "Raising children is not an easy task",
      wordType: "Adjective",
    },
    {
      id: 226,
      word: "rund",
      meaning: "round",
      example: "Das Rad ist nicht mehr hanz rund",
      translation: "The wheel is not round any more",
      wordType: "Adjective",
    },
    {
      id: 227,
      word: "frei",
      meaning: "free",
      example: "Der Platz neben mir ist noch frei",
      translation: "The place next to me is still free",
      wordType: "Adjective",
    },
    {
      id: 228,
      word: "früh",
      meaning: "early",
      example: "Sechs Uhr morgens? Das ist aber sehr früh!",
      translation: "Six o'clock in the morning? That's very early!",
      wordType: "Adjective",
    },
    {
      id: 229,
      word: "unterschiedlich",
      meaning: "different, variable",
      example: "Zum Bahnhof gelangt man mit unterschiedlichen Verkehrsmitteln",
      translation:
        "The train station can be reached by various means of transport",
      wordType: "Adjective",
    },
    {
      id: 230,
      word: "schlecht",
      meaning: "bad",
      example: "Die Menschen sind schlecht, alle denken nur an sich",
      translation: "People are bad, everyone thinks only about themselves",
      wordType: "Adjective",
    },
    {
      id: 231,
      word: "deutlich",
      meaning: "clear",
      example: "Kristin hat eine deutliche Aussprache",
      translation: "Kristin has a clear pronunciation",
      wordType: "Adjective",
    },
    {
      id: 232,
      word: "allgemein",
      meaning: "general",
      example: "Es ist allgemein bekannt, dass Paris in Frankreich liegt",
      translation: "It's well known that Paris is France",
      wordType: "Adjective",
    },
    {
      id: 233,
      word: "einzig",
      meaning: "only, single",
      example: "Gina ist das einzige Mädchen in der Klass",
      translation: "Gina is the only girl in the class",
      wordType: "Adjective",
    },
    {
      id: 234,
      word: "gemeinsam",
      meaning: "common, mutual",
      example: "Ein gemeinsamer Feind stärkt die Gruppe",
      translation: "A common enemy strengthens the group",
      wordType: "Adjective",
    },
    {
      id: 235,
      word: "nahe, nah",
      meaning: "near, close",
      example: "Weihnachten rückt immer näher",
      translation: "Christmas is getting closer and closer",
      wordType: "Adjective",
    },
    {
      id: 236,
      word: "voll",
      meaning: "full",
      example: "Die Flasche ist noch ganz voll",
      translation: "The bottle is still quite full",
      wordType: "Adjective",
    },
    {
      id: 237,
      word: "direkt",
      meaning: "direct, straight",
      example: "Wir gehen auf direktem Weg nach Hause",
      translation: "We're going straight home",
      wordType: "Adjective",
    },
    {
      id: 238,
      word: "international",
      meaning: "international",
      example: "Die Universität hat einen internationalen Anspruch",
      translation: "The university has an international claim",
      wordType: "Adjective",
    },
    {
      id: 239,
      word: "sozial",
      meaning: "social",
      example:
        "Bei Spendenaktionen wird gern an das soziale Gewissen der Spender appelliert",
      translation:
        "In fundraising campaigns, the social conscience of the donor is often appealed to",
      wordType: "Adjective",
    },
    {
      id: 240,
      word: "beste (r,s)",
      meaning: "best",
      example: "Meine Mutter macht den besten Currywurst der Welt",
      translation: "My mother makes the best currywurst in the world",
      wordType: "Adjective",
    },
    {
      id: 241,
      word: "rot",
      meaning: "red",
      example: "Rote Socken passen nicht zu blauen Schuhen",
      translation: "Red socks do not match blue shoes",
      wordType: "Adjective",
    },
    {
      id: 242,
      word: "offen",
      meaning: "open",
      example: "Die Flasche ist schon offen",
      translation: "The bottle is already open",
      wordType: "Adjective",
    },
    {
      id: 243,
      word: "meiste",
      meaning: "most",
      example: "Am meisten hat mir Richard gefallen",
      translation: "I liked Richard the most",
      wordType: "Adjective",
    },
    {
      id: 244,
      word: "besondere (r,s)",
      meaning: "special",
      example: "Barbara ist eine ganz besondere Frau",
      translation: "Barbara is a very special woman",
      wordType: "Adjective",
    },
    {
      id: 245,
      word: "öffentlich",
      meaning: "public",
      example: "Die Sitzung der Parlaments ist öffentlich",
      translation: "The sitting of Parliament shall be open to the public",
      wordType: "Adjective",
    },
    {
      id: 246,
      word: "halb",
      meaning: "half",
      example: "Wir gehen halb eins essen",
      translation: "We're going to eat half past 12",
      wordType: "Adjective",
    },
    {
      id: 247,
      word: "wahrscheinlich",
      meaning: "porbably",
      example: "Es wird wahrscheinlich eine Stunde dauern",
      translation: "It'll probably take an hour",
      wordType: "Adjective",
    },
    {
      id: 248,
      word: "wesentlich",
      meaning: "essential, fundamental",
      example: "Das ist ein ganz wesentlicher Unterschied",
      translation: "That is a very important difference",
      wordType: "Adjective",
    },
    {
      id: 249,
      word: "ähnlich",
      meaning: "similar",
      example: "Max sieht seinem Bruder ähnlich",
      translation: "Max looks like his brother",
      wordType: "Adjective",
    },
    {
      id: 250,
      word: "häufig",
      meaning: "frequent",
      example: "Hier werden häufige Wörter gesammelt",
      translation: "Common words are collected here",
      wordType: "Adjective",
    },
    {
      id: 251,
      word: "schwarz",
      meaning: "black",
      example: "Dort stand es schwarz auf weiß",
      translation: "There it was in black and white",
      wordType: "Adjective",
    },
    {
      id: 252,
      word: "völlig",
      meaning: "complete",
      example: "Das ist völlig Überflüssig",
      translation: "It's completely unnecessary",
      wordType: "Adjective",
    },
    {
      id: 253,
      word: "gering",
      meaning: "low, small",
      example: "Das ist ein geringes Problem",
      translation: "It's a minor problem",
      wordType: "Adjective",
    },
    {
      id: 254,
      word: "schwierig",
      meaning: "difficult",
      example: "Bowling ist schwieriger, als ich dachte",
      translation: "Bowling's harder than I thought",
      wordType: "Adjective",
    },
    {
      id: 255,
      word: "praktisch",
      meaning: "practical",
      example: "Ich finde kein praktisches Beispiel",
      translation: "I can't find a practical example",
      wordType: "Adjective",
    },
    {
      id: 256,
      word: "personlich",
      meaning: "personal",
      example: "Ich persönlich fand den Film gar nicht so schlecht",
      translation: "Personally, I didn't think the movie was so bad",
      wordType: "Adjective",
    },
    {
      id: 257,
      word: "modern",
      meaning: "modern",
      example: "Moderne Autos haben Airbags serienmäßig",
      translation: "Modern cars have airbags as standard",
      wordType: "Adjective",
    },
    {
      id: 258,
      word: "tief",
      meaning: "deep",
      example: "DasBaby schläft so tief, dass es nichts hört",
      translation: "The baby sleeps so soundly that it hears nothing",
      wordType: "Adjective",
    },
    {
      id: 259,
      word: "tatsächlich",
      meaning: "real, actual",
      example: "Er hat doch tatsächlich geheiratet!",
      translation: "He actually got married!",
      wordType: "Adjective",
    },
    {
      id: 260,
      word: "zusätzlich",
      meaning: "additional",
      example:
        "Zusätzlich zu seinem Studium absolvierte er noch drei freiwillige Praktika",
      translation:
        "In addition to his studies, he completed three voluntary internships",
      wordType: "Adjective",
    },
    {
      id: 261,
      word: "wirtschaftlich",
      meaning: "economic, financial",
      example: "China hat viele wirtschaftliche Probleme",
      translation: "China has many economic problems",
      wordType: "Adjective",
    },
    {
      id: 262,
      word: "interessant",
      meaning: "interesting",
      example: "Interessante Diplomarbeiten sind selten",
      translation: "Interesting diploma theses are rare",
      wordType: "Adjective",
    },
    {
      id: 263,
      word: "relativ",
      meaning: "relative",
      example: "Meine Wohnung ist relativ klein",
      translation: "My apartment is relatively small",
      wordType: "Adjective",
    },
    {
      id: 264,
      word: "gleichzeitig",
      meaning: "simultaneous",
      example: "Sie sprangen gleichzeitig von der Brücke",
      translation: "They jumped off the bridge at the same time",
      wordType: "Adjective",
    },
    {
      id: 265,
      word: "grün",
      meaning: "green",
      example: "Die Bäume werden grün",
      translation: "The trees turn green",
      wordType: "Adjective",
    },
    {
      id: 266,
      word: "weiß",
      meaning: "white",
      example: "Schneewittchens Haut war weiß wie Schnee",
      translation: "Snow White's skin was white as snow",
      wordType: "Adjective",
    },
    {
      id: 267,
      word: "gesamt",
      meaning: "whole, entire",
      example: "Die gesamte Universität musste evakuiert werden",
      translation: "The entire university had to be evacuated",
      wordType: "Adjective",
    },
    {
      id: 268,
      word: "speziell",
      meaning: "special, specific",
      example: "Das ist eine sehr spezielle Frage",
      translation: "That's a very specific question",
      wordType: "Adjective",
    },
    {
      id: 269,
      word: "entscheidend",
      meaning: "decisive",
      example:
        "Der entscheidende Vorteil für Investition lag in den Steuervergünstigung",
      translation:
        "The decisive advantage of investment lay in the tax concession",
      wordType: "Adjective",
    },
    {
      id: 270,
      word: "eng",
      meaning: "narrow, close",
      example: "Er ist ein enger Verwandter",
      translation: "He's a close relative",
      wordType: "Adjective",
    },
    {
      id: 271,
      word: "technisch",
      meaning: "technical",
      example: "Das ist ein technisches Problem",
      translation: "It's a technical problem",
      wordType: "Adjective",
    },
    {
      id: 272,
      word: "langsam",
      meaning: "slow",
      example: "Faultiere bewegen sich sehr langsam",
      translation: "Sloths move very slowly",
      wordType: "Adjective",
    },
    {
      id: 273,
      word: "ständig",
      meaning: "constant",
      example: "Ich denke ständig an dich",
      translation: "I'm always thinking about you",
      wordType: "Adjective",
    },
    {
      id: 274,
      word: "notwendig",
      meaning: "necessary",
      example: "Das ist jetzt nicht mehr notwendig",
      translation: "This is no longer necessary",
      wordType: "Adjective",
    },
    {
      id: 275,
      word: "rein",
      meaning: "pure, clean",
      example: "Das ist ja reines Wasser!",
      translation: "That's pure water!",
      wordType: "Adjective",
    },
    {
      id: 276,
      word: "wissenschaftlich",
      meaning: "scientific, scholarly",
      example: "Wissenschaftliche Aufsätze sind oft schwer zu lesen",
      translation: "Scientific essays are often difficult to read",
      wordType: "Adjective",
    },
    {
      id: 277,
      word: "falsch",
      meaning: "false, wrong",
      example: "Ich habe eine falsche Adresse angegeben",
      translation: "I gave a wrong address",
      wordType: "Adjective",
    },
    {
      id: 278,
      word: "fremd",
      meaning: "foreign",
      example: "Ich will eine fremde Sprache lernen",
      translation: "I want to learn a foreign language",
      wordType: "Adjective",
    },
    {
      id: 279,
      word: "selten",
      meaning: "rare",
      example: "Jens schaut selten fern",
      translation: "Jens rarely watches TV",
      wordType: "Adjective",
    },
    {
      id: 280,
      word: "normal",
      meaning: "normal",
      example: "Heute ist ein ganz normaler Tag",
      translation: "It's just a normal day today",
      wordType: "Adjective",
    },
    {
      id: 281,
      word: "wahr",
      meaning: "true",
      example: "Das kann doch nicht wahr sein",
      translation: "This can't be true",
      wordType: "Adjective",
    },
    {
      id: 282,
      word: "privat",
      meaning: "private",
      example: "Das ist meine private E-Mail Adresse",
      translation: "That's my private e-mail address",
      wordType: "Adjective",
    },
    {
      id: 283,
      word: "tot",
      meaning: "dead",
      example: "Wagner ist seit 121 Jahren tot",
      translation: "Wagner has been dead for 121 years",
      wordType: "Adjective",
    }
  ],
}
